In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import v_measure_score
from sklearn.metrics.cluster import contingency_matrix

In [40]:
class kohonen:

    def __init__(
        self,
        M,
        N,
        X,
        learning_rate=0.1,
        gauss_neighborhood_function=True,
        neighborhood_proximity=1.0,
        lattice="rectangular",
    ):
        self.M = M
        self.N = N
        self.learning_rate = learning_rate
        self.input_dim = X.shape[1]
        if gauss_neighborhood_function:
            self.neighborhood_function = self.gauss_neighborhood
        else:
            self.neighborhood_function = self.mexican_hat_neighborhood
        self.neighborhood_proximity = neighborhood_proximity
        # its not working like this
        # self.lattice_distances = np.zeros((M, N))
        self.calculate_lattice_distances(M, N, lattice)
        self.weights = np.random.uniform(0, 1, (self.input_dim, M, N))
        minimum = np.min(X, axis=0)
        maximum = np.max(X, axis=0)
        for i in range(self.input_dim):
            self.weights[i] = minimum[i] + (maximum[i] - minimum[i]) * self.weights[i]

    def calculate_lattice_distances(self, M, N, lattice):
        if lattice == "rectangular":
            pass
        elif lattice == "hexagonal":
            pass
        else:
            raise ValueError("Invalid lattice type")

    def gauss_neighborhood(self, distance, epoch):
        return np.exp(-np.power(distance * epoch * self.neighborhood_proximity, 2))

    def mexican_hat_neighborhood(self, distance, epoch):
        return np.exp(-np.power(distance * epoch * self.neighborhood_proximity, 2)) * (
            2 - 4 * np.power(distance * epoch * self.neighborhood_proximity, 2)
        )

    def euclidean_distance(self, x, y):
        return np.linalg.norm(x - y)

    def decay(self, t, iteration_num):
        return self.learning_rate * np.exp(-t / iteration_num)

    def train(self, X, max_epochs):
        for epoch in range(max_epochs):
            X = np.random.permutation(X)
            decay_value = self.decay(epoch, max_epochs)
            for x in X:
                idx = np.argmin(np.linalg.norm(self.weights.T - x, axis=2).T)
                bmu = np.unravel_index(idx, self.weights[0].shape)

                for i in range(self.M):
                    for j in range(self.N):
                        distance_on_lattice = self.euclidean_distance(
                            np.array(bmu), np.array([i, j])  # old approach change it
                        )
                        self.weights[:, i, j] += (
                            decay_value
                            * self.neighborhood_function(distance_on_lattice, epoch)
                            * (x - self.weights[:, i, j])
                        )

    def predict(self, X):
        return np.array(
            [
                [
                    np.argmin(
                        [
                            self.euclidean_distance(x, self.weights[:, i, j])
                            for i in range(self.M)
                            for j in range(self.N)
                        ]
                    )
                    for x in X
                ]
            ]
        ).T

## tests with numpy and speed 

In [8]:
cube = pd.read_csv("./../data/kohonen/cube.csv")
cube_x = cube.drop("c", axis=1).to_numpy()
kohon = kohonen(2, 4, cube_x)
weights = kohon.weights
weights

array([[[-1.01156814,  2.66328134,  2.38491856,  0.96708048],
        [ 1.93136495,  2.71473683,  2.05809027,  0.0631648 ]],

       [[-1.56559317,  0.87695878,  3.59341698,  4.21392388],
        [ 4.05699271, -0.33768321, -0.51779918,  5.54942807]],

       [[ 2.9794021 ,  0.55741637,  1.93910687, -1.23854172],
        [ 2.7368817 , -1.32376104,  2.11437958,  0.04835879]]])

In [9]:
x = cube_x[40]
for i in range(2):
    for j in range(4):
        distance = kohon.euclidean_distance(x, weights[:, i, j])
        print(f"Distance from {i}, {j}: {distance}")

Distance from 0, 0: 3.5558179704295325
Distance from 0, 1: 2.866371117384524
Distance from 0, 2: 5.442909346943757
Distance from 0, 3: 5.560814488417281
Distance from 1, 0: 6.074152819974137
Distance from 1, 1: 2.4542857746727833
Distance from 1, 2: 2.602766244666087
Distance from 1, 3: 6.808399161649306


In [10]:
np.linalg.norm(weights.T - x, axis=2).T

array([[3.55581797, 2.86637112, 5.44290935, 5.56081449],
       [6.07415282, 2.45428577, 2.60276624, 6.80839916]])

In [11]:
idx = np.argmin(np.linalg.norm(weights.T - x, axis=2).T)
np.unravel_index(idx, weights[0].shape)

(1, 1)

### Testing if i broke something 

In [12]:
kohon = kohonen(2, 4, cube_x)
kohon.train(cube_x, 10)
cube["predicted"] = kohon.predict(cube_x)
v_measure_score(cube["c"], cube["predicted"])

0.9184550780838783

# getting rid of second loop

In [14]:
bmu = (0, 1)
for i in range(2):
    for j in range(4):
        distance_on_lattice = kohon.euclidean_distance(
            np.array(bmu), np.array([i, j])  # old approach change it
        )
        print(f"Distance from {i}, {j}: {distance_on_lattice}")

Distance from 0, 0: 1.0
Distance from 0, 1: 0.0
Distance from 0, 2: 1.0
Distance from 0, 3: 2.0
Distance from 1, 0: 1.4142135623730951
Distance from 1, 1: 1.0
Distance from 1, 2: 1.4142135623730951
Distance from 1, 3: 2.23606797749979


In [23]:
# create a matrix of distances from the BMU without looping
bmu = (0, 1)
np.arange(4).repeat(2).reshape(4, 2).T

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [25]:
np.arange(2).repeat(4).reshape(2, 4)

array([[0, 0, 0, 0],
       [1, 1, 1, 1]])

In [29]:
# create a 3d numpy array with the two above arrays
(
    np.array(
        [np.arange(4).repeat(2).reshape(4, 2).T, np.arange(2).repeat(4).reshape(2, 4)]
    ).T
    - np.array(bmu)
).T

array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3]],

       [[-1, -1, -1, -1],
        [ 0,  0,  0,  0]]])

In [39]:
bmu = (3, 1)
M = 4
N = 4
np.linalg.norm(
    (
        np.array(
            [
                np.arange(N).repeat(M).reshape(N, M).T,
                np.arange(M).repeat(N).reshape(M, N),
            ]
        ).T
        - np.array(bmu)
    ),
    axis=2,
).T

array([[3.16227766, 2.23606798, 1.41421356, 1.        ],
       [3.        , 2.        , 1.        , 0.        ],
       [3.16227766, 2.23606798, 1.41421356, 1.        ],
       [3.60555128, 2.82842712, 2.23606798, 2.        ]])